errorLog = false
volume = 1.0
maxPlayCont = 8
spatial = true
subtitleType = "OFF"
youtubeSubtitleLanguage = "AUTO"
relayServerURL = "https://raw.githubusercontent.com/TeamFelnull/IamMusicPlayer/master/relay_server.json"
maxWaitTime = 10000
retryTime = 3000
dropItemRing = true
patchouliIntegration = true
